<style>
    #carousel {
        max-width: 1000px;
        margin: 20px auto;
        box-shadow: 0 0 5px 0px;
    }
    .link-button {
        font-size: 24px;
        background: #444444;
        padding: 8px 20px;
        border-radius: 16px;
        box-shadow: 0 0 5px 0;
        margin: 20px auto;
        display: inline-block;
    }
    .link-button span {
        color: white;
    }
    .link-button:hover {
        text-decoration: none;
    }
</style>

<?php
$segment = $block->getThisSegment();
?>

<div class="large light frame">
    <div class="head">
        <?php echo $segment['name']; ?>
    </div>
    <div class="text">
        <?php echo $segment['html_content']; ?>
    </div>

    <?php
    $images = $block->getSegmentImages();
    if (count($images) > 0) { ?>
        <div id="carousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <?php
                foreach ($images as $i => $item) {
                    $class = ($i == 0) ? 'class="active"' : '';
                    echo "<li data-target='#carousel' data-slide-to='$i' $class></li>";
                }
                ?>
            </ol>
        <div class="carousel-inner">
            <?php foreach ($images as $i => $item) {
                $class = ($i == 0) ? 'active' : '';
                ?>
                <div class="carousel-item <?php echo $class; ?>">
                    <img class="d-block w-100" src="/<?php echo $item['image_uri']; ?>">
                </div>
            <?php } ?>
        </div>
        <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
        </div>
    <?php } ?>
    <a href="<?php echo $block->getContactLink(); ?>" class="link-button">
        <span>Kontakt Os</span>
    </a>
</div>
