<style>
    .segment_previews .item {
        display: block;
        color: white;
        background: #444;
        height: 200px;
        margin-bottom: 28px;
        line-height:200px;
        text-align: center;
        font-size: 30px;
        font-weight: 600;
        box-shadow: 0 0 10px black;
        transition: box-shadow 0.2s;

        background-size: cover;
        background-position: center;    
    }
    .segment_previews .item:hover {
        box-shadow: 0 0 18px black;
    }
    .segment_previews .item > span {
        vertical-align: middle;
    }
</style>
<div class="row segment_previews">
    <?php
    $segments = $block->getActiveSegments();
    foreach ($segments as $i => $segment) {
        $columnClass = 'col-12 col-lg-6';
        if (($i + 1) == count($segments)) { // Last preview only
            $columnClass = 'col';
        }
        echo "<span class='$columnClass'>
            <a href='".$block->getSegmentUrl($segment)."' 
                class='item' 
                style='background-image: url(/{$segment['thumbnail_uri']})'
            >
                <span>{$segment['name']}</span>
            </a>
        </span>";
    }
    ?>
</div>